"""empty message

Revision ID: 3696af0a25e
Revises: 4398a3254d73
Create Date: 2015-06-15 16:16:14.052245

"""

# revision identifiers, used by Alembic.
revision = '3696af0a25e'
down_revision = '4398a3254d73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_date_user_can',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_date_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_date_id'], ['game_date.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_date_user_can')
    ### end Alembic commands ###
